package:
  name: ska.file  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}


build:
  preserve_egg_dir: yes
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.File



requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - Ska.File

about:
  home: https://github.com/sot/Ska.File
