package:
  name: agasc
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  script_env:
    - USER
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/agasc


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - six
    - numpy
    - numexpr
    - pytables
    - ska_path
    - chandra.time
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - pytables
    - numpy
    - numexpr
    - chandra.time
    - ska_path
    - astropy
    - testr

test:
  imports:
    - agasc


about:
  home: https://github.com/sot/agasc

